In [78]:
# se importan todas las librerias
import pandas as pd 
import numpy as np
import kagglehub
import os

In [79]:
# descargar ultima version de ventas
path = kagglehub.dataset_download("chadwambles/supermarket-sales")
print(os.listdir(path))

['Creation Queries.sql', 'Customer Behavior KPIs.sql', 'Product Performance KPIs.sql', 'Sales and Revenue KPIs.sql', 'sales.csv']

In [80]:
# creo un dataframe con el archivo csv descargado
df =pd.read_csv(path + "/sales.csv")

In [81]:
# muestro el dataframe 
df.head()

,sale_id,branch,city,customer_type,gender,product_name,product_category,unit_price,quantity,tax,total_price,reward_points
0,1,A,New York,Member,Male,Shampoo,Personal Care,5.50,3,1.16,17.66,1
1,2,B,Los Angeles,Normal,Female,Notebook,Stationery,2.75,10,1.93,29.43,0
2,3,A,New York,Member,Female,Apple,Fruits,1.20,15,1.26,19.26,1
3,4,A,Chicago,Normal,Male,Detergent,Household,7.80,5,2.73,41.73,0
4,5,B,Los Angeles,Member,Female,Orange Juice,Beverages,3.50,7,1.72,26.22,2

In [82]:
df.columns

Index(['sale_id', 'branch', 'city', 'customer_type', 'gender', 'product_name',
       'product_category', 'unit_price', 'quantity', 'tax', 'total_price',
       'reward_points'],
      dtype='object')

In [83]:
# visualización de datos
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   sale_id           1000 non-null   int64
 1   branch            1000 non-null   object
 2   city              1000 non-null   object
 3   customer_type     1000 non-null   object
 4   gender            1000 non-null   object
 5   product_name      1000 non-null   object
 6   product_category  1000 non-null   object
 7   unit_price        1000 non-null   float64
 8   quantity          1000 non-null   int64
 9   tax               1000 non-null   float64
 10  total_price       1000 non-null   float64
 11  reward_points     1000 non-null   int64
dtypes: float64(3), int64(3), object(6)
memory usage: 93.9+ KB

In [84]:
# cambiar nombres de encabezados


df = df.rename(columns={
    'sale_id':'Id_ventas',
    'branch': 'Rama', 
    'city':'ciudad',
    'customer_type':'Tipo_de_cliente', 
    'gender': 'genero', 
    'product_name':'nombre_producto',
    'product_category':'categoria_producto', 
    'unit_price':'precio_unitario', 
    'quantity':'cantidad', 
    'tax':'impuesto', 
    'total_price':'precio_total',
    'reward_points':'puntos'
})

In [86]:
tipo_cliente = df['Tipo_de_cliente'].unique().tolist()
lista_genero = df['genero'].unique().tolist()
categoria_prod = df['categoria_producto'].unique().tolist()
productos = df['nombre_producto'].unique().tolist()

tipo_cliente_NEW = ['Miembro','Normal']
lista_genero_NEW = ['Masculino','Femenino']
categoria_prod_NEW = ['Cuidado personal','Papelería','Frutas','Hogar','Bebidas' ]
productos_NEW = ['Shampoo','Cuaderno','Manzana','Detergente','Jugo de naranja']

In [87]:
# reemplazar valores en ingles
def reemplazar (viejos, nuevos, df,  columna):
    df[columna] = df[columna].replace(viejos,nuevos)
    
reemplazar(tipo_cliente,tipo_cliente_NEW,df,'Tipo_de_cliente')    
reemplazar(lista_genero,lista_genero_NEW,df,'genero')
reemplazar(categoria_prod,categoria_prod_NEW,df,'categoria_producto')
reemplazar(productos,productos_NEW,df,'nombre_producto')

In [89]:
df.loc[df['nombre_producto'] == 'Shampoo','categoria_producto'] = 'Cuidado personal'
df.loc[df['nombre_producto'] == 'Cuaderno','categoria_producto'] = 'Papelería'
df.loc[df['nombre_producto'] == 'Manzana','categoria_producto'] = 'Frutas'
df.loc[df['nombre_producto'] == 'Detergente','categoria_producto'] = 'Hogar'
df.loc[df['nombre_producto'] == 'Jugo de naranja','categoria_producto'] = 'Bebidas'

In [ ]:
df.to_excel('tienda.xlsx')

,Id_ventas,Rama,ciudad,Tipo_de_cliente,genero,nombre_producto,categoria_producto,precio_unitario,cantidad,impuesto,precio_total,puntos
0,1,A,New York,Miembro,Masculino,Shampoo,Cuidado personal,5.50,3,1.16,17.66,1
1,2,B,Los Angeles,Normal,Femenino,Cuaderno,Papelería,2.75,10,1.93,29.43,0
2,3,A,New York,Miembro,Femenino,Manzana,Frutas,1.20,15,1.26,19.26,1
3,4,A,Chicago,Normal,Masculino,Detergente,Hogar,7.80,5,2.73,41.73,0
4,5,B,Los Angeles,Miembro,Femenino,Jugo de naranja,Bebidas,3.50,7,1.72,26.22,2
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,A,New York,Miembro,Femenino,Shampoo,Cuidado personal,1.55,11,1.19,18.24,1
996,997,A,New York,Miembro,Masculino,Detergente,Hogar,2.44,7,1.20,18.28,1
997,998,A,New York,Miembro,Femenino,Shampoo,Cuidado personal,17.92,2,2.51,38.35,3
998,999,A,New York,Miembro,Femenino,Shampoo,Cuidado personal,17.41,4,4.87,74.51,7
999,1000,A,New York,Normal,Masculino,Jugo de naranja,Bebidas,4.11,4,1.15,17.59,0